In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import datetime
from pandas.tools.plotting import table

In [2]:
df=pd.read_csv("sfpd_dispatch_data_subset.csv") #create dataframe

In [3]:
df.dispatch_timestamp=pd.to_datetime(df.dispatch_timestamp)
df.on_scene_timestamp=pd.to_datetime(df.on_scene_timestamp)

In [4]:
times= pd.DataFrame(df['on_scene_timestamp']-df['dispatch_timestamp']) #find length of time using time delta

In [5]:
times['address'] = df['address']

In [6]:
times.dropna(inplace=True)#remove Nat values

In [7]:
times['minutes'] = (times[0].dt.total_seconds()/60) #convert timedelta to minutes

In [8]:
avg_times=times.groupby('address', as_index=False)['minutes'].mean()#find avg by group

In [9]:
avg_times.sort_values('minutes', inplace=True, ascending=False)

In [10]:
avg_times

                               address    minutes
1029             2100 Block of 45TH AV  50.483333
1180      2600 Block of BAY SHORE BLVD  38.983333
590              1300 Block of UTAH ST  37.866667
884                   1ST ST/FOLSOM ST  36.216667
1724             600 Block of 11TH AVE  35.766667
2475                 ORTEGA ST/48TH AV  32.183333
1341           300 Block of SERRANO DR  31.816667
1339           300 Block of RALSTON ST  31.700000
393            1000 Block of LARKIN ST  29.800000
1998             900 Block of MARIN ST  29.000000
2044             BAYSHORE BL/ARLETA AV  28.516667
2181               FERN ST/VAN NESS AV  27.616667
940             200 Block of HARBOR RD  27.333333
950   200 Block of LAKE MERCED HILL ST  26.133333
2274              HARBOR RD/INGALLS ST  26.000000
1608              500 Block of 10TH ST  25.633333
146                 0 Block of NAVY RD  25.266667
1265              300 Block of 3RD AVE  24.716667
1797           600 Block of SANSOME ST  24.650000
2598                  TREAT AV/24TH ST  24.566667
2534          SAN BRUNO AV/DIVISION ST  24.566667
1882            700 Block of NATOMA ST  24.525000
402            1000 Block of PALOU AVE  24.500000
1947          800 Block of MOULTRIE ST  24.333333
2505                POLK ST/PACIFIC AV  24.016667
2137                CRISP AV/REVERE AV  23.916667
141                0 Block of MINT PLZ  23.794444
1364         3000 Block of FILLMORE ST  23.616667
825          1800 Block of JENNINGS ST  23.416667
1323           300 Block of LOMBARD ST  23.250000
...                                ...        ...
2468                OCTAVIA ST/PINE ST   0.483333
1417             3500 Block of 18TH ST   0.416667
2386               MARKET ST/CASTRO ST   0.266667
2278                HARRISON ST/3RD ST   0.183333
2620               VAN NESS AV/BUSH ST   0.166667
2496                   PINE ST/POLK ST   0.150000
2106       CESAR CHAVEZ ST/VALENCIA ST   0.150000
2082             CALIFORNIA ST/LYON ST   0.116667
535                  12TH AV/IRVING ST   0.000000
2395               MARKET ST/KEARNY ST   0.000000
554          1300 Block of BRUSSELS ST   0.000000
2312              JERROLD AV/RANKIN ST   0.000000
2028                 9TH ST/MISSION ST   0.000000
1594                  47TH AV/GEARY BL   0.000000
1451             3800 Block of 26TH ST   0.000000
1088                22ND ST/POTRERO AV   0.000000
2270           HAIGHT ST/DIVISADERO ST   0.000000
1211          2700 Block of PACHECO ST   0.000000
2051             BAYSHORE BL/TUNNEL AV   0.000000
98                 0 Block of HENRY ST   0.000000
2488           PARNASSUS AV/HILLWAY AV   0.000000
2365               LINCOLN WY/GREAT HY   0.000000
1136               24TH ST/BARTLETT ST   0.000000
1135                24TH ST/ALABAMA ST   0.000000
1809          600 Block of TOWNSEND ST   0.000000
826          1800 Block of JERROLD AVE   0.000000
2115            CHURCH ST/RESERVOIR ST   0.000000
2588                 SUTTER ST/HYDE ST   0.000000
882                 19TH ST/FLORIDA ST   0.000000
2364                LINCOLN WY/10TH AV   0.000000

[2649 rows x 2 columns]